from dataclasses import dataclass, field
import os
import json
from typing import Self


# Named dict for HTTPBasicAuth requirements
@dataclass
class BasicAuth:
    username:str
    password:str

    @classmethod
    def load(self, path:str):
        assert os.path.exists(path), "File path does not exist"

        with open(path, 'r') as f:
            auth = json.loads(f.read())

        assert auth.get("username") and auth.get("password"), "Fields `username` and `password` were not found. Ensure both are present in your auth json file!"

        return BasicAuth(username=auth.get("username"), password=auth.get("password"))

    def dict(self):
        return vars(self)

# Named dict for project management via a token
@dataclass
class TokenConfig:
    token:str
    project_name:str

    @classmethod
    def load(self, path:str):
        assert os.path.exists(path), "File path does not exist"

        with open(path, 'r') as f:
            token = json.loads(f.read())

        assert token.get("project_name") and token.get("token"), "Fields `project_name` and `token` were not found. Ensure both are present in your token json file!"

        return TokenConfig(project_name=token.get("project_name"), token=token.get("token"))

    def dict(self):
        return vars(self)

    def auth_header(self):
        return {"Authorization": f"Bearer {self.token}"}

# Named dict for new project requirements
@dataclass
class ProjectConfig:
    hacker_email:str
    project_name:str
    project_summary:str
    
    @classmethod
    def load(self, path:str):
        assert os.path.exists(path), "File path does not exist"

        with open(path, 'r') as f:
            project = json.loads(f.read())

        assert project.get("project_name") and project.get("project_summary") and project.get("hacker_email"), "Fields `project_name` and `project_summary` and `hacker_email` were not found. Ensure both are present in your project json file!"

        return ProjectConfig(project_name=project.get("project_name"), project_summary=project.get("project_summary"), hacker_email=project.get("hacker_email"))

    def dict(self):
        return vars(self)

# Named dict for Feed/Batch endpoint payloads
@dataclass
class FeedPayload:
    page:int = 1 
    batch_count:int = 10
    events: list[dict] = field(default_factory=list)
    search_prompt: str = ""

    def dict(self):
        return vars(self)



@dataclass
class Event:
    """Concrete wrapper for event system

    Main args:
        - `event`
        - `id`
        - `organization_id`
        - `session_id`
        - `visitor_id`,
        - `weight`

    By default `event` is set to be "abstract interest"

    All other fields must be set manually

    The `Event.create()` method allows you to create an `Event` class via a function with out specifying the `event` property
    """
    id: str
    organization_id: str
    session_id: str
    visitor_id: str
    weight: int
    event: str = "abstract interest"

    def dict(self):
        return {
            "event": self.event,
            "properties": {
                "id": self.id,
                "organization_id": self.organization_id,
                "session_id": self.session_id,
                "visitor_id": self.visitor_id,
                "weight": self.weight
            }
        }

    @classmethod
    def create(self,
               id:str,
               organization_id:str,
               session_id:str,
               visitor_id:str,
               weight:int) -> Self:
        return Event(id=id, organization_id=organization_id, session_id=session_id, visitor_id=visitor_id, weight=weight)
    

@dataclass
class WebsocketPayload:
    """Create a websockey payload defined in API 2.0

    Main Args:
        - `id`
        - `type`
        - `search_prompt`
        - `events`

    Techincally all arguments have defaults, however some of the usage is undefined
    I believe `id` fields will be autogenerated but may require tracking
    `search_prompt` field is not always needed
    
    """
    id: str | None = None
    type: str = "socket_pagination_request"
    search_prompt: str = ""
    events: list[Event] = field(default_factory=list)

    def dict(self):
        return {**vars(self), "events": [event.dict() for event in self.events]}
    
